version: '2'
services:
    timesheet-app:
        image: timesheet
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://timesheet-mariadb:3306/timesheet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timesheet-mariadb:
        extends:
            file: mariadb.yml
            service: timesheet-mariadb
